urlDictList:
  - modelName: linear-regression
    modelUrl: http://admin:admin@10.60.150.177:31112/function/lr
  - modelName: support-vector-machine
    modelUrl: http://admin:admin@10.60.150.177:31112/function/svr
  - modelName: random-forest
    modelUrl: http://admin:admin@10.60.150.177:31112/function/rf
  - modelName: lstm
    modelUrl: http://admin:admin@10.60.150.177:31112/function/lstm
