openFaaSGateway: 10.60.150.177:31112
openFaaSBasicAuth:
  user: admin
  password: admin
prometheusGateway: 10.60.150.177:31119
db:
  version: MySQL
  host: 10.60.150.177
  port: 3306
  user: root
  password: root
  database: modeldb
  charset: utf8
